### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bangive** [taoliuh/VolleyImageUtils#1]
Please add docs to let me understand how to use this image util. Thank you.

**Comment by taoliuh** [comment]
It's not supposed to be a repo. It's just a gist. Actually there is one useful method compress.The compress method simply scales down the bitmap with its origin ratio, then compress and write into file. You should specify  the max width and max height. You can ignore other methods.

**Comment by bangive** [comment]
Which one is better: This gist vs [Whatsapp like Image Compression in Android with demo](http://voidcanvas.com/whatsapp-like-image-compression-in-android/)

**Comment by taoliuh** [comment]
mine is better, the one you quoted is hard coded. You can check the new update, i just refactored and push new features.

**Comment by bangive** [comment]
Great, i like watermark feature very much.
About compress feature. I like to compress and save to other path not override the original image. Could you add this feature.

**Comment by taoliuh** [comment]
It's easy, already added.

**Comment by bangive** [comment]
Thank you very much. I think you miss a comma at the line 276:
`public static void compress(String originPath, String outputPath int maxWidth, int maxHeight, int quality) {`

**Comment by taoliuh** [comment]
Yep.

**Comment by bangive** [comment]
I think crop function is helpful. Could you add it?

**Comment by taoliuh** [comment]
sure, pr is welcome.
